#!/usr/bin/env bash
#It displays numbers from 1 to 20 with some peculiarities
count=1
while [ $count -lt 101 ] 
do
	if (( count % 5 == 0 )) && (( count % 3 == 0 ))
	then
		echo "FizzBuzz"
	elif (( count % 3 == 0 ))
	then
		echo "Fizz"
	elif (( count % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $count
	fi
	
	((count+=1))
done
