#!/usr/bin/env bash
#This script is displaying "Best School" 10 times.
less /etc/passwd | while IFS=: read -r p1 p2 p3 p4 p5 p6 p7
do 
	echo "The user $p1 is part of the $p4 gang, lives in $p6 and rides $p7. $p3's place is protected by the passcode $p2, more info about the user here: $p5"
done
