#!/usr/bin/env bash
#Listing processes
sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
deleteandkill(){ sudo rm /var/run/myscript.pid; exit; }
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'deleteandkill' SIGQUIT
done
